name: luacheck
on: [push, pull_request]
jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Luacheck
        run: |
          docker run --rm -it -u luacheck --mount="type=bind,source=$(pwd),target=/repo" mineunit/luacheck